# Archivo: nixpacks.toml
# Le indica a Railway que instale paquetes adicionales del sistema.

[phases.setup]
# 'aptPkgs' es la lista de paquetes de sistema que se instalarán.
# Aquí le pedimos que instale 'ffmpeg'.
aptPkgs = ["ffmpeg"]

[start]
# Comando para iniciar tu aplicación una vez construido el entorno.
cmd = "python bot.py"